version: "3"
volumes:
  dbdata: {}

services:
  nginx:
    restart: always
    build: 
      context: ./dockerfiles/nginx/
    ports:
      - "8003:80"
    networks:
      - default
  app:
    build: 
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
    environment:
      WEB_CONCURRENCY: 1
      DB_HOST: 'db'
      DB_NAME: 'outlook'
      DB_USER: 'scriptum'
      DB_PASSWORD: 'scriptumdbpass'
      # default pass of 'user' is 'pass'
      BASIC_AUTH_user: 'd74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1'
    # ports: 
    # - "8003:8000"
    volumes:
    - ./src:/app/
    networks:
      - default
      - eprotocol_db_network
networks:
  eprotocol_db_network:
    name: eprotocol_backend
    external: true